server:
  servlet:
    context-path: /Dome5

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: accp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #hibernate:
    #ddl-auto: create
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
